# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pathlib import Path
import os, sys

# Obtenir le chemin absolu du répertoire parent
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
sys.path.insert(0, project_root)

from config.KeyInputLineEdit import KeyInputLineEdit

# Chemin absolu vers l'icône
ressources_path = Path(__file__).parent.parent / "ressources"

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(416, 502)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(str(ressources_path)+"/AppIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Settings.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(Settings)
        self.gridLayout.setObjectName("gridLayout")
        self.right = QtWidgets.QLabel(Settings)
        self.right.setObjectName("right")
        self.gridLayout.addWidget(self.right, 4, 0, 1, 1)
        self.takeoff = QtWidgets.QLabel(Settings)
        self.takeoff.setObjectName("takeoff")
        self.gridLayout.addWidget(self.takeoff, 0, 0, 1, 1)
        self.land = QtWidgets.QLabel(Settings)
        self.land.setObjectName("land")
        self.gridLayout.addWidget(self.land, 1, 0, 1, 1)
        self.left = QtWidgets.QLabel(Settings)
        self.left.setObjectName("left")
        self.gridLayout.addWidget(self.left, 5, 0, 1, 1)
        self.backward = QtWidgets.QLabel(Settings)
        self.backward.setObjectName("backward")
        self.gridLayout.addWidget(self.backward, 3, 0, 1, 1)
        self.forward = QtWidgets.QLabel(Settings)
        self.forward.setObjectName("forward")
        self.gridLayout.addWidget(self.forward, 2, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Settings)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 6, 1, 1, 1)
        self.takeoffInput = KeyInputLineEdit(Settings)
        self.takeoffInput.setObjectName("takeoffInput")
        self.gridLayout.addWidget(self.takeoffInput, 0, 1, 1, 1)
        self.landInput = KeyInputLineEdit(Settings)
        self.landInput.setObjectName("landInput")
        self.gridLayout.addWidget(self.landInput, 1, 1, 1, 1)
        self.forwardInput = KeyInputLineEdit(Settings)
        self.forwardInput.setObjectName("forwardInput")
        self.gridLayout.addWidget(self.forwardInput, 2, 1, 1, 1)
        self.backwardInput = KeyInputLineEdit(Settings)
        self.backwardInput.setObjectName("backwardInput")
        self.gridLayout.addWidget(self.backwardInput, 3, 1, 1, 1)
        self.rightInput = KeyInputLineEdit(Settings)
        self.rightInput.setObjectName("rightInput")
        self.gridLayout.addWidget(self.rightInput, 4, 1, 1, 1)
        self.leftInput = KeyInputLineEdit(Settings)
        self.leftInput.setObjectName("leftInput")
        self.gridLayout.addWidget(self.leftInput, 5, 1, 1, 1)

        self.retranslateUi(Settings)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Settings"))
        self.right.setText(_translate("Settings", "Droite"))
        self.takeoff.setText(_translate("Settings", "Décoller"))
        self.land.setText(_translate("Settings", "Atterir"))
        self.left.setText(_translate("Settings", "Gauche"))
        self.backward.setText(_translate("Settings", "Reculer"))
        self.forward.setText(_translate("Settings", "Avancer"))

